use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::net::IpAddr;

/// Represents a captured network packet with extracted features
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PacketInfo {
    pub timestamp: DateTime<Utc>,
    pub source_ip: IpAddr,
    pub destination_ip: IpAddr,
    pub source_port: Option<u16>,
    pub destination_port: Option<u16>,
    pub protocol: Protocol,
    pub size_bytes: usize,
    pub payload_hash: Option<String>,
    pub flags: Option<u8>,
    pub ttl: Option<u8>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Protocol {
    Tcp,
    Udp,
    Icmp,
    Other(u8),
}

impl std::fmt::Display for Protocol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Protocol::Tcp => write!(f, "TCP"),
            Protocol::Udp => write!(f, "UDP"),
            Protocol::Icmp => write!(f, "ICMP"),
            Protocol::Other(n) => write!(f, "OTHER({})", n),
        }
    }
}

/// Features extracted from traffic for ML analysis
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrafficFeatures {
    pub connection_count: u32,
    pub packet_count: u32,
    pub avg_packet_size: f64,
    pub std_packet_size: f64,
    pub unique_ports: u16,
    pub unique_destinations: u32,
    pub bytes_per_second: f64,
    pub packets_per_second: f64,
    pub syn_ratio: f64,
    pub fin_ratio: f64,
    pub rst_ratio: f64,
    pub port_entropy: f64,
    pub time_window_secs: u64,
}

impl TrafficFeatures {
    pub fn to_feature_vector(&self) -> Vec<f64> {
        vec![
            self.connection_count as f64,
            self.packet_count as f64,
            self.avg_packet_size,
            self.std_packet_size,
            self.unique_ports as f64,
            self.unique_destinations as f64,
            self.bytes_per_second,
            self.packets_per_second,
            self.syn_ratio,
            self.fin_ratio,
            self.rst_ratio,
            self.port_entropy,
        ]
    }
}

/// Severity levels for alerts
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub enum Severity {
    Low = 1,
    Medium = 2,
    High = 3,
    Critical = 4,
}

impl std::fmt::Display for Severity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Severity::Low => write!(f, "LOW"),
            Severity::Medium => write!(f, "MEDIUM"),
            Severity::High => write!(f, "HIGH"),
            Severity::Critical => write!(f, "CRITICAL"),
        }
    }
}

/// Alert generated by the detection system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub severity: Severity,
    pub alert_type: AlertType,
    pub source_ip: Option<IpAddr>,
    pub destination_ip: Option<IpAddr>,
    pub description: String,
    pub details: AlertDetails,
    pub score: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AlertType {
    RuleBased { rule_id: String, rule_name: String },
    AnomalyBased { model_version: String },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlertDetails {
    pub triggered_features: Vec<String>,
    pub feature_deviations: Vec<FeatureDeviation>,
    pub raw_features: Option<TrafficFeatures>,
    pub recommendation: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeatureDeviation {
    pub feature_name: String,
    pub expected_value: f64,
    pub actual_value: f64,
    pub deviation_score: f64,
    pub explanation: String,
}

/// Statistics for a network flow
#[derive(Debug, Clone, Default)]
pub struct FlowStats {
    pub packet_count: u64,
    pub byte_count: u64,
    pub start_time: Option<DateTime<Utc>>,
    pub end_time: Option<DateTime<Utc>>,
    pub syn_count: u32,
    pub fin_count: u32,
    pub rst_count: u32,
}

/// Detection result with AI reasoning
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectionResult {
    pub detected: bool,
    pub confidence: f64,
    pub reason: String,
    pub pattern: String,
    pub severity: Severity,
    pub indicators: Vec<String>,
}

/// Context-rich alert with full network details
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrichedAlert {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub severity: Severity,
    pub alert_type: AlertType,
    pub source_ip: IpAddr,
    pub destination_ip: IpAddr,
    pub source_port: Option<u16>,
    pub destination_port: Option<u16>,
    pub protocol: Protocol,
    pub description: String,
    pub details: AlertDetails,
    pub detection_result: DetectionResult,
    pub score: f64,
}

/// Aggregated alert group (for deduplication)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AggregatedAlert {
    pub group_id: String,
    pub alert_type: String,
    pub severity: Severity,
    pub description: String,
    pub source_ips: Vec<IpAddr>,
    pub destination_ports: Vec<u16>,
    pub count: usize,
    pub first_seen: DateTime<Utc>,
    pub last_seen: DateTime<Utc>,
    pub sample_alert: EnrichedAlert,
    pub detection_result: DetectionResult,
}

/// Time-series data point for sparklines
#[derive(Debug, Clone, Default)]
pub struct MetricPoint {
    pub timestamp: DateTime<Utc>,
    pub value: f64,
}

/// System metrics for TUI
#[derive(Debug, Clone, Default)]
pub struct SystemMetrics {
    pub packets_per_second: f64,
    pub alerts_per_second: f64,
    pub active_connections: u32,
    pub suspicious_ips: u32,
    pub pps_history: Vec<MetricPoint>,
    pub aps_history: Vec<MetricPoint>,
}

/// Top threat entry
#[derive(Debug, Clone)]
pub struct TopThreat {
    pub source_ip: IpAddr,
    pub threat_type: String,
    pub severity: Severity,
    pub count: usize,
    pub last_seen: DateTime<Utc>,
}
